version: '3.7'

services:
  # Spring Boot Application
  app:
    image: your-spring-boot-app-image:latest  # Replace with your app's image name if you have built the image
    build: /Users/saisreepothireddygari/Documents/monitoringapp  # If you are building the image locally, adjust path accordingly
    container_name: spring-boot-app
    ports:
      - "8080:8080"  # Expose Spring Boot app on port 8080
    networks:
      - monitoring-network

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount your prometheus.yml file
    ports:
      - "9090:9090"  # Expose Prometheus on port 9090
    networks:
      - monitoring-network

  
  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Optional: Set admin password
    ports:
      - "3000:3000"  # Expose Grafana on port 3000
    networks:
      - monitoring-network
    depends_on:
      - prometheus

    
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring-network
    expose:
      - "9100"
    command:
      - "--web.listen-address=:9100"

networks:
  monitoring-network:
    driver: bridge

